server:
  port: 9083

spring:
  application:
    name: odontologos
  datasource:
    url: jdbc:mysql://localhost:3306/cdent_odontologos?serverTimezone=UTC&useSSL=false&createDatabaseIfNotExist=true
    username: root
    password: 
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml